#!/usr/bin/env bash

. "$(dirname $0)/include/base"

$(dirname $0)/exec rm var/log/*
$(dirname $0)/console --env=dev doctrine:database:drop --force --if-exists --no-interaction
$(dirname $0)/console --env=dev doctrine:database:create --if-not-exists --no-interaction
$(dirname $0)/console --env=dev doctrine:migrations:migrate --no-interaction
