version: "3"

services:
    nginx:
        image: nginx:stable
        ports:
            - 80:80
        volumes:
            - ../:/var/www/macpawtest
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build:
            context: ..
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ../:/var/www/macpawtest
        depends_on:
            - db
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=dbpass
        volumes:
            - db-data:/var/lib/mysql/

volumes:
    db-data:
        driver: local
